remote_theme  : "poole/hyde"
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marveloping
tagline:          'A Jekyll theme'
description:      'Online marketer learns the code.'
url:              "http://nukzan.github.io"
baseurl:          /

author:
  name:           'Nukzan'
  url:            https://github.com/nukzan

paginate:         5

# Custom vars
version:          2.1.0

#github:
 # repo:           https://github.com/poole/hyde
